# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: pay_android
description: A plug-in to add support for payments on the Android side of Flutter applications.
version: 1.0.7
homepage: https://github.com/google-pay/flutter-plugin

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=2.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.pay_android
        pluginClass: PayPlugin

  assets:
    - assets/
    - assets/en/
    - assets/ar/
    - assets/bg/
    - assets/ca/
    - assets/cs/
    - assets/da/
    - assets/de/
    - assets/el/
    - assets/es/
    - assets/et/
    - assets/fi/
    - assets/fr/
    - assets/hr/
    - assets/id/
    - assets/it/
    - assets/ja/
    - assets/ko/
    - assets/ms/
    - assets/nl/
    - assets/no/
    - assets/pl/
    - assets/pt/
    - assets/ru/
    - assets/sk/
    - assets/sl/
    - assets/sr/
    - assets/sv/
    - assets/th/
    - assets/tr/
    - assets/uk/
    - assets/zh/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pay_platform_interface: ^1.0.2
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  flutter_lints: ^2.0.1
